# Generated by Django 5.0.4 on 2024-04-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code_1', models.CharField(max_length=20)),
                ('hex_code_2', models.CharField(max_length=20)),
                ('hex_code_3', models.CharField(max_length=20)),
                ('hex_code_4', models.CharField(max_length=20)),
                ('hex_code_5', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
